name: Build & Tests

on:
  push:
  schedule:
    - cron: '0 0 * * *' # every day at 00:00


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Install libjava-gnome-java
        run: sudo apt-get install libjava-gnome-java
      - name: Build
        run: bazel build //...
      - name: Run Tests
        run: bazel test //...
